name: CI

on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master, CI ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redisgraph:
        image: redislabs/redisgraph:latest
        ports:
          - 6379:6379

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.0.4
      - run: julia -e 'println("Hello, World!")'
